### ISSUE TITLE
[Clarification] Batch request across multiple service roots

### ISSUE THREAD

**Issue by falbert-ptc** [oasis-tcs/odata-specs#2028]
Hello,

I have a somewhat unusual question. 

Let's say I have 2 OData services at _http://host/service1/_ and at _http://host/service2_.
Those services reference each other in the metadata, in the EDMX references. For example in _service2_:
`    <edmx:Reference Uri="http://host/service1/$metadata">
        <edmx:Include Namespace="service1"/>
    </edmx:Reference>`

Is it intended/supported by the spec to have a batch request in _service1_ that would have individual requests both in _service1_ and _service2_ ?
For example:
`POST http://host/service1/$batch

--batch_1
Content-Type: multipart/mixed;boundary=changeset_1

--changeset_1
Content-ID: 1_1
Content-Transfer-Encoding: binary
Content-Type: application/http

POST http://host/service1/EntitySet1 HTTP/1.1
Accept: application/json
Content-Type: application/json

{<entityRep>}

--changeset_1
Content-ID: 1_2
Content-Transfer-Encoding: binary
Content-Type: application/http

POST http://host/service2/EntitySet2 HTTP/1.1
Accept: application/json
Content-Type: application/json

{ 
"nav@odata.bind":"$1_1"
}
--changeset_1--
--batch_1--
`

For what it's worth, in my example, both _service1_ and _service2_ are on the same host.

The [spec ](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_BatchRequests) does not explicitly states that all individual requests within a batch must have the same base URI as batch service root. 
In 11.7 it says `Individual requests within a batch request are evaluated according to the same semantics used when the request appears outside the context of a batch request.`.
And in 11.7.7.1, example 98 it says `Absolute URI with schema, host, port, and absolute resource path.`.

So it does not explicitly prohibit it, so I was wondering if that use case was supported and intended by the spec (setting aside all technical implementation complications that can come with it).

Thank you

**Comment by ralfhandl** [comment]
Hello @falbert-ptc,

Mixing requests to different services in a batch is possible from a specification perspective. The spec doesn't call that out because there can/will be implementation-specific boundary conditions on what can be mixed, by whom, to which extent, ...

SAP's ABAP implementation of OData V4 does allow this under special conditions, and these conditions are independent of the existence of cross-service references.

There's nothing preventing you from also allowing cross-service batch requests, and you can define your own conditions on what you allow, and your own mechanisms on how to convey that to clients of your APIs.

Hope this helps!

**Comment by falbert-ptc** [comment]
Thanks @ralfhandl !
