### ISSUE TITLE
Casting of common expressions

### ISSUE THREAD

**Issue by HeikoTheissen** [oasis-tcs/odata-specs#405]
The section [OData-URL, Common Expression Syntax](https://oasis-tcs.github.io/odata-specs/odata-url-conventions/odata-url-conventions.html#CommonExpressionSyntax) contains no rules for casting of expressions that are part of a bigger expression. (It only contains rules for "numeric promotion".)

For expressions with a given signature (arithmetic operators and functions), it is unclear whether arguments are implicitly casted (so that `2 add '3'` would evaluate to 5) or whether a wrong argument type makes the expression invalid.

For the logical operators `eq`, `ne`, `lt`, `le`, `gt`, `ge` and `in`, it is unclear whether
- arguments of different types make the expression invalid
- or (for `eq`, `ne` and `in`) arguments of different types (numbers, strings, booleans, enum values) are always unequal
- or arguments are casted before comparison, but in which direction? `'4.0'  eq 4` is true when casted to numbers but false when casted to strings.

**Comment by ralfhandl** [comment]
Please cross-check with https://docs.oasis-open.org/odata/odata/v4.02/csd01/part2-url-conventions/odata-v4.02-csd01-part2-url-conventions.html#cast if there are any gaps that this issue can be used to close.

**Comment by mikepizzo** [comment]
I feel strongly that, in cases where the metadata is known, services should return an error if the comparison is not valid, rather than silently returning a null -- I don't want a mistake I make in writing my url (i.e., mistaking id for a string instead of a number) and have the service happily return an empty result rather than tell me there was something wrong.
